### ISSUE TITLE
I've Updated to Modern GL - Works with Kodi 18 on Linux

### ISSUE THREAD

**Issue by glk1001** [xbmc/visualization.goom#14]
Hi,

I've fixed the code in your master branch to work with modern GL and Kodi 18. I've tested this on Ubuntu 19.04 and Libreelec 9.1 and it's good. Haven't done Windows or mac.

Is this of any use to you guys?

Greg

**Comment by notspiff** [comment]
Hi,

yes for sure. PR most welcome.

tir. 23. jul. 2019, 03:33 skrev glk1001 <notifications@github.com>:

**Comment by glk1001** [comment]
Hi,

I've never done a PR before. In order to do a PR, Github desktop wants me
to publish a branch with my changes but I don't have permission.

What do I need to do?

Thanks,
Greg

**Comment by glk1001** [comment]
Hi, figured it out. There is a now a pull request waiting.

Thanks,
Greg

**Comment by AlwinEsch** [comment]
Hi @glk1001 have few questions about your rework.

What the reason to make "AddRequest" two times, see: https://github.com/xbmc/visualization.goom/blob/Leia/src/Main.cpp#L299-L300?

Also, I noticed in the "UpdateGoomBuffer" and "Worker" a very high CPU usage, always 100% and have a hack with Sleep temporarily to reduce it a little. Is this normal and can it be fixed somehow?

Also, the frequency representation in the lines does not seem correct, only very, very small.

About lines (now):
![Screenshot_20191003_195005](https://user-images.githubusercontent.com/6879739/66151215-20c61700-e617-11e9-816e-aac137a00ffc.png)

Before:
![screenshot-04](https://user-images.githubusercontent.com/6879739/66151354-6da9ed80-e617-11e9-808f-b7a00edf2a52.png)

**Comment by glk1001** [comment]
Hi Alwin,

Unfortunately I can't quite remember the reason for the two AddRequests
(sadly I should have added a comment). I did explicitly make a note of the
two AddRequests in a git commit comment so I did it deliberately. Calls to
"goom_update" with the same data will give different outputs because of
calls to Random so maybe it gave a smoother appearance having two
AddRequests. You could try with just one AddRequest and see what happens.

I think "goom_update" is very CPU intensive which is one of the reasons I
added the worker threads. Without the workers, Goom looked very slow on my
NUC NUC6CAYH. But as long as all the CPUs aren't 100% isn't that OK?

After I first got Goom working with the newer OpenGL I noticed the
frequency representation looked bad. It was large and had odd large jumps.
It looks better smaller but I may have just hidden a bug.

I can have a look these issues if you like.

And thanks for all your work.

Greg

**Comment by AlwinEsch** [comment]
Looked at my check that with `m_worker.AddRequest` given audio data does not arrive correctly at` goom_update` and this does not fit 100%, think that was your reason to make the call twice. Also, this is called unnecessarily often (in the render ()) which also no new audio data was present and the CPU lands at 100%.

The wrong frequency display comes from the goom itself, had once reset to the previous one and was then back to normal.

I have a very disgusting change here, so do not see it as a real change (only temporary): https://github.com/xbmc/visualization.goom/pull/18/commits/e361887a0aa14ff221bd1396343df2eed83d886d

Just as an example, as there CircularBuffer.h can always give the right needed audio size.
Also was the performance better.

**Comment by AlwinEsch** [comment]
Think this issue no more needed.
